New html pages
williamzhu17/repo-with-tapas pull request #2
Opened 2021-02-15 22:42 UTC by williamzhu17

Finished fixing the loop error and turned the list into a table on the user-details.html page.

2021-02-16 07:24 UTC, atapas requested changes

2021-02-16 07:24 UTC, atapas commented on html/registration.html
> +    <form name="form" action="user-details.html" onsubmit="return validateForm()">
Why do we have to return the validateForm here?

2021-02-16 15:18 UTC, williamzhu17 commented on html/registration.html
> +    <form name="form" action="user-details.html" onsubmit="return validateForm()">
It is to check if the username has been taken already or not. I use the username as the key for obtaining the user details in localStorage, so I have to prevent multiple people from registering with the same username.

2021-02-17 11:04 UTC, atapas approved these changes

2021-02-17 20:41 UTC, merged